# Generated by Django 5.0.3 on 2024-03-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emission_nom',
            fields=[
                ('emission_nom_id', models.AutoField(primary_key=True, serialize=False)),
                ('emission_nom_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='fuel_types',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_types',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_details',
            fields=[
                ('vehicle_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('vin_no', models.CharField(max_length=17, unique=True)),
                ('registration_no', models.CharField(max_length=12, null=True)),
                ('address', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=8)),
                ('model_name', models.CharField(max_length=20)),
                ('engine_no', models.CharField(max_length=15)),
                ('making_date', models.DateField()),
                ('is_onboard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emission_nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle_service.emission_nom')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle_service.fuel_types')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle_service.vehicle_types')),
            ],
        ),
    ]
